---
title: "class notes"
author: "Elise Haylett"
date: "2/12/2020"
output: html_document
---
```{r}
library(combinat)
library(prob)
```

Permutation, Order matters
```{r, factorial - base r}
factorial(2)
factorial(3)
factorial(4)
factorial(52)
factorial(1000) # Out of range
```

```{r}
permn(4)
(length(permn(4)))
permn(c("a", "b", "c", "d"))
```

```{r}
permsn(c("a", "b", "c", "d"), 4)
factorial(4) / factorial(4)
permsn(c("a", "b", "c", "d"), 3)
permsn(c("a", "b", "c", "d"), 2)
permsn(c("a", "b", "c", "d"), 1)
# permsn(c("a", "b", "c", "d"), 0) # gets an error because system has no way of showing "no objects" results in NULL
```


Combination, Order doesn't matter
```{r, choose base code}
choose(4, 0)
choose(4, 1)
choose(4, 2)
choose(4, 3)
choose(4, 4)
choose(4, 5)
```

```{r}
combn(4, 2)
```

```{r, class notes 2/13}
dbinom(0, 3, 1/3)
8/27

dbinom(1, 3, 1/3)
12/27

dbinom(2, 3, 1/3)

dbinom(3, 3, 1/3)

```

```{r}
dbinom(0:3, 3, 1/3)
rockprob <- data.frame(x = 0:3,
           f_x = dbinom(0:3, 3, 1/3),
           F_x = pbinom(0:3, 3, 1/3))
```

```{r}
game_sims <- rbinom(100000, 3, 1/3)
game_sims

prop.table(table(game_sims))
mean(game_sims)
sd(game_sims)
```






