---
title: "Class Notes"
author: "Elise Haylett"
date: "1/22/2020"
output: html_document
---

```{r, characters}
#character vectors
people_names <- c("Bob", "Alice", "Joe")
people_names
print(people_names)

#To get just Bob
people_names[1]

#to get just Bob and Joe
people_names[1, 3] #ERROR, R thinks its a matrix
people_names[c(1, 3)]
people_names[-2]
```





```{r, integers}
my_integers <- c(2, 6, 18)
my_decimals <- c(18.2, 10, 16.5)
```





```{r, logical}
my_logical <- c(TRUE, TRUE, FALSE)
```





```{r, computations}
2 * my_integers
my_integers_2x <- 2 * my_integers

my_integers^2
sqrt(my_integers)


my_integers * my_decimals
```





```{r, ERROR}
#if you try to multiple a numeric vector to a string
my_integers * people_names

#multiplying a numeric to a logical
my_integers * my_logical #works because TRUE = 1, FALSE = 0
#result will be a number and not a logical
```





```{r}
#you can add all vectors to a list
my_list <- list(people_names, my_decimals, my_integers, my_logical)

#dataframe is a special kind of list where all vectors have to be the same length... other characteristics make so where there are variables

#ctrl + l clears the console


#creating a dataframe

my_dataframe <- data.frame(people_names, my_decimals, my_integers, my_logical)
colnames(my_dataframe) <- c("name", "decimals", "integers", "logical")
```





```{r}
: #special kind of sequence
  #sequence of integers. from:to
seq() # sequence
rep() # repeat


v1to100 <- 1:100
v100to1 <- 100:1

seq(0, 100, by = 10)
seq(1, 100, length.out = 20) #to only have 20 values
seq(1, 100, by = .1)
```





```{r}
rep(people_names, 2)
rep(people_names, each = 2)
rep(people_names, times - c(1,2,3))

```





```{r}
n <- 10^5
chr_results <- character(n)
num_results <- numeric(n)
int_results <- integer(n)
log_results <- 3
logical(n)
```





```{r}
plays <- c("rock", "paper", "scissors")

#sample(x, size, replace = FALSE, prob = NULL)
#prob = NULL means that all values have an equal chance of being pick
# sample(plays)
sample(plays, 1, prob = c(.5, .25, .25))
```





```{r}
for (i in 1:10) {
  player1 <- sample(plays, 1)
  player2 <- sample(plays, 1)
  print(c(player1, player2))
}
```




```{r}
#set the number of loops

number_of_loops <- 10^5

#initialize vectors to hold results
player1 <- character(number_of_loops)
player2 <- character(number_of_loops)

#run the sampling/simulation loop

for (i in 1:number_of_loops) {
  player1[i] <- sample(plays, 1)
  player2[i] <- sample(plays, 1)
}

table(player1)
table(player2)

rps_game <- data.frame(player1, player2)
```

